version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm run dev"
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
